### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by iiiMatt** [iiiMatt/WiSe-2023-24#1]
# Data preprocessing
The `titanic.csv` should be preprocessed before the data analysis in the `preprocessing.R` file.
Following steps should be taken:
 - **Salutation extraction**: The salutation should be extracted from the name ("Mr.", "Mrs.", "Ms." etc...), later they will be used to infer the missing age of some people. Note that some of the salutation are the same contentwise (e.g. "Ms." and "Miss."). The salutation "Master" describes a young boy. The extracted salutation should be saved into a new variable called "_Salutation_".
 - **Variable encoding**: The variables „_Survived_“, „_Sex_“ and „_Embarked_“ should be encoded into factors and "Pclass" into an ordered-factor (1  > 2 > 3).
 - **Age inferrence**: Using the newly created "_Salutation_" variable the age should be inferred, for example by taking the mean or the median for each salutation.
 - **Cabin data extraction**: The following data should be extracted from the variable "_Cabin_":
   - "_Port_" or "_Starboard_": if the "_Cabin_" is odd it's on the "_Port_" otherwise it's on the "_Starboard_"
   - "_Deck_": leading letter of the cabin number. In case of missing letter it should be `NA`
 - **Cleanup**: Remove the variables "_PassengerID_", "_Name_", "_Ticket_" and "_Cabin_" from the dataset.
 - **Saving**: The final dataset should be saved in a new file.

**Comment by miamacarena** [comment]
We should merge the code regarding preprocessed data to the main branch if it is done.  I created a check list so we can follow the next steps. It would be good if the three people who programmed this part can finish up the last few steps as well since the rest does not know which lines to merge exactly. 

- [ ] finish up the code 
- [ ] merge request  and finish up merge
- [ ] delete data preprocessing branch
