### ISSUE TITLE
5) Discussion 

### ISSUE THREAD

**Issue by helen-mza** [iiiMatt/WiSe-2023-24#30]
Discuss the results of the repository and add new ideas.

**Comment by miamacarena** [comment]
Hi everyone-
to get the discussion started I am going to recap my approach and results. I split it into two comments about the two parts i have had so everyone can reply directly to those comments, give feedback and maybe add new ideas. 

It would be helpful if you also add a reference @miamacarena or whoever to it to make sure the person sees it.

**Comment by miamacarena** [comment]
I was supposed to focus on the functions from 2 iii) and iv). In this comment I start with 

**iii)**
The function I used here was _chisq_test_plus_table()_ and outputs a contingency table and the result of a chi squared test regarding associations between two categorical variables. 

### I compared the following variables:

- Survived and Embarked 
- Survived and Salutation

The categorical variables deck and side had many NAs which is why I did not use them for my analysis.

### Results
_Survived and Embarked:_ 
- More survivors then dead of people who embarked Cherbourg. 
- other cities more dead than survivors (Southhampton 2  out of 3) 
-  very low p-value: statistically significant evidence
-> that there is a significant relationship between  embarkation and survival

_Salutation and Survival_
- 2 out of 10 Mister, 6 out of 10 Master died 
- majority of women survived 
- Theory/Hypothesis: Female passenger got helped to get to the boats., men with a title might as well and most men died to rescue or let the female go ahead. 
- also: less female than men: when they are prioritized ratio goes up quicker
- very low p value: statistically significant evidence
-> that there is a significant relationship between  salutation and survival

**Comment by miamacarena** [comment]
**iv)**
In  iv) I called the function _calculateBivariateStats()_ with a a dichotomous and metric variable. It splits the metric variable in groups by using the dichotomous variable and outputs the mean, sd and the results of a t-test. 

### I compared the following variables:

- Fare and Survived
- Age and Survived

### Results

_Fare and Survived_

- individuals who died paid in average much less for their tickets than the ones who survived
- sd of survivers regarding fare is big: apparently still some survivors with much cheaper or even much more expensive fare
- SD of people who died is much smaller: seems like the people who paid the most got rescued first and barely died or even not at all
- pvalue very low: indicates that the true difference in means between the groups is not equal to zero 
- expresses the results before: apparently fare price made a difference to survival 
- Theory/Hypothesis: likely that the rich people and women got rescued first suits the society back then

_Age and Survived_

- survivors slightly younger: difference around two years
- Theory/Hypothesis: might because of children who are usually rescued first?
- both groups with mean of 28 and 30 young (but expected age younger back then)
- p-value = 0.02358 lower than the adjusted pvalue (Bonferroni adjusment to 0.0125)
- not enough evidence against the null hypothesis that the true difference in means between the groups is equal to zero (maybe there was not enough data )

**Comment by smnehong** [comment]
@miamacarena This all seems very consistent to me, especially women and children being rescued first and also wealthier people being rescued first. I don’t know if that makes sense but the low evidence of correlation between age and survival could be due to the fact that a lot of the age values are imputed.
I think it would be interesting to see if there is a correlation between Embarked and Fare. If Cherbourg was where the richer people borded the ship this would explain why most of them survived.

**Comment by Loguy007** [comment]
I was in charge of analyzing 2 v) and vi). I start with :

v)

The function I used here was visualisation_categorial_variable() and the objective was to visualize the categorial variables (sex, embarked, pclass, survived). I therefore created 6 graphs in total.

•	3 give us the graphical representation of survivors according to their sex, class and place of embarkation . 
•	the 3 other give us the representation of non-survivors according to sex, place of embarkation and class. 

### _RESULT_:

Survived and sex:
•	Of the 342 people who survived, 68% were women and 32% men, and of the 549 dead, 85% were men and 15% women. So more men died than women. My hypothesis is: women were given priority during the rescue.

Survived and Pclass
•	68% of deaths were in class 3 compared with only 18% in class 2 and 15% in class 1. I think that those who paid the most were also prioritized during the rescue.

Survived and embarked
•	78% of the dead embarked at Southampton compared with 9% for Queenstown  and 14% for Cherbourg. I think there is a positive correlation between the place of embarkation at Southampton and class 3 (the majority of people in class 3 embarked at Southampton).

**Comment by Loguy007** [comment]
vi)

Here we have two functions Mosaikplot() and Boxplots_with_Trendline (). The goal is to visualize a variable of our choice according to another variable.

I visualize the following variables:

•	Fare with pclass , sex and survive
•	Sex with pclass and embarked
•	Pclass with embarked

### _Results_

Fare and pclass , sex and survive:
•	The correlation between ticket price and class is positive (the more you want to be in a good class, the more you have to pay)

•	Women generally paid more for tickets than men. This could justify the fact that women were given priority over men during the rescue operation.

•	In general, those who survived were those who paid the highest ticket prices.
this is in line with the fact that the survival rate in class 1 was high and the death rate low.  

Sex and pclass , embarked:
•	There were more people (both men and women) in class 3. I don't think that's very surprising given that this class is the least expensive

•	The majority of people(man as woman) had embarked in Southampton. So it's not surprising that the death rate from this place of embarkation is the highest.

 Pclass  with embarked:
•	The majority of people who embarked at Southampton or Queenstown were in class 3, whereas at Cherbourg almost half the passengers were in class 1. We can understand why Southampton has a high mortality rate and Cherbourg a low mortality rate, since in v) we saw that the mortality rate is higher in Southampton and in class 3. Hypothesis 3 is therefore confirmed

**Comment by Loguy007** [comment]
@smnehong You are perfectly right . In my analysis i discovered that the majority of people who embarked at Cherbourg were in class 1, i.e. the rich, and as the more you have paid, the quicker they try to save you, which explains why there are relatively large numbers of them who have survived in class 1.

**Comment by miamacarena** [comment]
@Loguy007 Your graphical results not only support my theories based on my results but also added some more detail. It seems like we have a proper analysis, that adds up to a good result! You even answered the great idea @smnehong mentioned in his comment before you added your results.

**Comment by Loguy007** [comment]
@miamacarena  My graphical analysis really confirms your calculations - great job!

**Comment by helen-mza** [comment]
My analysis for metric variables mainly showed that Fare had a lot of dispersion and a very big range (ranged to over 500). Quartiles are quite low at around 8 and 31 so there were a lot of people with cheaper fares.
The categorial variables that were unevenly distributed were Embarked (mode is Southhampton), Salutation (mode is Mr.), Deck (mode is C) and Pclass (mode is 3) a bit but Deck and Side have a lot of NA values and don't show anything. Embarked could support your findings @Loguy007 about @smnehong's hypothesis because it means most people embarked at Southhampton. This matches the fact that most people paid a lower fare and most people had a lower class.

**Comment by Johanna2208** [comment]
Well done - I think the analysis yields good results.
